name = "hlpfl-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = "frontend/.next"

[env.production]
name = "hlpfl-frontend"
route = "portal.hlpfl.org/*"

[env.staging]
name = "hlpfl-frontend-staging"
route = "staging-portal.hlpfl.org/*"

[[env.production.vars]]
NEXT_PUBLIC_API_URL = "https://api.hlpfl.org"

[[env.staging.vars]]
NEXT_PUBLIC_API_URL = "https://staging-api.hlpfl.org"